name: "node_maria_project"

services:
  database:
    image: mariadb:11
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "3307:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "db_maria"

  backend:
    # build:
    # context: ./
    # dockerfile: Dockerfile
    image: node:22-alpine
    env_file:
      - .env
    environment:
      - JWT_KEY=${JWT_KEY}
    ports:
      - "8080:8081"
    volumes:
      - ./backend:/backend
      - node_modules:/backend/node_modules
    depends_on:
      database:
        condition: service_healthy
    command: 'sh -c "cd backend && npm i && npm run start"'
volumes:
  node_modules:
